FROM node:20 

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY prisma ./prisma/

# Install app dependencies
RUN npm install prisma
RUN npm install dotenv-cli

