version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_DB=median-db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
      
  nest-api:
    image: nest-api:latest

    # enable building mode. if you want to just pull and hot start, disable this code.
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile

    # run migration command
    command: npm run start:prod
    
    # run reset command
    # command: >
    #       bash -c "npx prisma migrate reset --force
    #       && npm run start:prod"

    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env.development
      
volumes:
  postgres:
