version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_DB=median-db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nest-api:
    stdin_open: true
    tty: true
    image: nest-api:latest

    # enable building mode. if you want to just pull and hot start, disable this code.
    container_name: nest-api
    build:
      context: .
      dockerfile: DockerFile

    command: npm run start:dev

    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env.development

  prisma-studio:
    image: prisma-studio:latest

    # enable building mode. if you want to just pull and hot start, disable this code.
    container_name: prisma-studio
    build:
      context: .
      dockerfile: DockerFile.prisma-studio

    command: npx dotenv-cli -e .env.studio -- npx prisma studio

    ports:
      - 5555:5555
    depends_on:
      - postgres
    env_file:
      - .env.development

volumes:
  postgres:
