version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_DB=median-db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
      
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    command: >
          bash -c "npx prisma migrate dev --name 'docker-inner-init'
          && npm run start:prod "
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env
      
volumes:
  postgres:
